Valgrind support for the test suite. valgrind gets used when called as "make check TESTS_STYLE=valgrind"

diff --git a/tests/functions b/tests/functions
--- a/tests/functions
+++ b/tests/functions
@@ -1,14 +1,26 @@
 
-
 BASEDIR=$(dirname $0)
 if [ -z "$RRDTOOL" ] ; then 
-	RRDTOOL=$BASEDIR/../src/rrdtool
+	case "$TESTS_STYLE" in
+	valgrind)
+		echo >&2 "# Note: exit code 111 indicates a valgrind detected memory problem" 
+		RRDTOOL="libtool --mode=execute valgrind --tool=memcheck \
+			--suppressions=$BASEDIR/valgrind-supressions \
+			--leak-check=full --show-reachable=yes \
+			--leak-resolution=high --num-callers=20 \
+			--error-exitcode=111 --log-file=/dev/null \
+			$BASEDIR/../src/rrdtool"
+		;;
+	*)
+		RRDTOOL=$BASEDIR/../src/rrdtool
+		;;
+	esac
 fi
 
 DIFF="diff -u"
 
 function fail {
-	echo >&2 "FAILED:" "$@"
+	echo >&2 "FAILED: (rc=$?)" "$@"
 	if [ -n "$CONTINUE" ] ; then
 		return
 	fi
