add/update tests

diff --git a/tests/functions b/tests/functions
--- a/tests/functions
+++ b/tests/functions
@@ -1,14 +1,25 @@
 
+
 BASEDIR=$(dirname $0)
 RRDTOOL=$BASEDIR/../src/rrdtool
 
+DIFF="diff -u"
+INTERACTIVE=
+
 function fail {
-	 echo >&2 "FAILED:" "$@"
-	 exit 1
+	echo >&2 "FAILED:" "$@"
+	if [ -n "$INTERACTIVE" ] ; then
+		read -p "Continue? (y/n)" YN
+		if [ "$YN" != 'y' ] ; then 
+			exit 1
+		fi
+	else
+		exit 1
+	fi
 }
 
 function ok {
-	 echo >&2 "OK:" "$@"
+	echo >&2 "OK:" "$@"
 }
 
 function report {
